handling table name

diff --git a/create_table b/create_table
--- a/create_table
+++ b/create_table
@@ -8,6 +8,13 @@ then
 table_name=$(echo "$table_name" | tr ' ' '_')
 fi
 
+ while ! [[ $table_name =~ ^[a-zA-Z_][a-zA-Z0-9_]*$ ]]; 
+  do
+    echo "Error: $table_name is not in the correct format."
+    echo "Please try again."
+    read table_name
+  done
+
 # -e is to make sure that table name is unique
 # -e ==> exists 
 while [[ -e "$table_name" ]]
