help me

diff --git a/delete_data b/delete_data
--- a/delete_data
+++ b/delete_data
@@ -1,24 +1,43 @@
 #!/bin/bash
 
-# List all the available tables
-read -a tables <<< "$(ls | grep '\.table$')"
+shopt -s nullglob
+tables=( *.table )
+
 
 # Check if there are any tables
-if [[ ${#tables[@]} -eq 0 ]]; then
+if [[ ${#tables[@]} -eq 0 ]]
+then
   echo "No tables found."
-  exit 1
+  exit
 fi
 
 # Display the tables
-echo "Available tables:"
-for ((i=0; i<${#tables[@]}; i++)); do
-  echo "$((i+1)). ${tables[i]}"
-done
+
+#  ${} --> means variable 
+#  # -> means number
+#  tables[@] --> means each member of the array
+  echo "Available tables:"
+  for (( i=0; i<${#tables[@]}; i++ ))
+    do
+      echo "$((i+1)). ${tables[i]}"
+    done
+
 
 # Ask for the table selection
 while true; do
   echo "Enter the number of the table you want to manage:"
   read selection
+      while ! [[ $selection =~ ^[1-9]+$ ]]; do
+          echo "Error: $selection must be positive."
+          echo "Please try again."
+          read selection
+          while [[ -z $selection ]]
+          do
+            echo "Cannot be Empty !! "
+            echo "Please try again."
+            read selection
+          done
+      done
 
   # Check if the selection is valid
   if [[ $selection -ge 1 && $selection -le ${#tables[@]} ]]; then
@@ -31,11 +50,25 @@ while true; do
 done
 
 # Display options for managing the table
-echo "Select an option:"
-echo "1. Delete a specific row"
-echo "2. Delete all data"
-echo "3. Delete all specific column"
-read option
+
+    echo "Select an option:"
+    echo "1. Delete a specific row"
+    echo "2. Delete all data"
+    echo "3. Delete all specific column"
+    read option
+
+    while ! [[ $option =~ ^[1-9]+$ ]]; do
+        echo "Error: $selection must be positive."
+        echo "Please try again."
+        read option
+        while [[ -z $option ]]
+        do
+          echo "Cannot be Empty !! "
+          echo "Please try again."
+          read option
+        done
+    done
+
 
 case $option in
   1)
@@ -59,7 +92,6 @@ case $option in
 
   2)
     # Delete all rows (except first row)
-    
     sed -i '2,$d' "$table_name"
     echo "Data of $table_name deleted successfully"
     ;;
